<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_spin</name>
   <tag></tag>
   <elementGuidId>eb818790-11ac-42a9-b24c-20221b0a8181</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'mydiv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fe527023-3761-41d0-94f1-d423b8cf4f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mydiv</value>
      <webElementGuid>203c8ca6-3874-468c-a80d-a2b4ebfb6f97</webElementGuid>
   </webElementProperties>
</WebElementEntity>
