<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_username</name>
   <tag></tag>
   <elementGuidId>ce2ab355-58a1-4d44-9c5f-ddaf5e098e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class, 'login-name')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>81cce9d2-2527-42e3-8d8c-a7c1ae7f44f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-name</value>
      <webElementGuid>0f174944-c23e-4ce4-9c97-e0396da129c0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
