<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_disabled_submit</name>
   <tag></tag>
   <elementGuidId>a4c09e65-2c7b-42b9-bc4d-80617a940c92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@type = 'button' and @class = 'btn button btn-secondary disabled']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>73a0d080-4308-468c-94db-33548afaa180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>91a9667b-5412-424c-a5bd-3f7e654900a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button btn-secondary disabled</value>
      <webElementGuid>70aa1a11-b240-4aea-b713-d913fb83724e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
