<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_confirm</name>
   <tag></tag>
   <elementGuidId>51404cbe-c39c-48c6-9d0d-a43e02360d3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type = 'button' and @id = 'confirm'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@type = 'button' and @id = 'confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc5a415e-df10-4f67-b48a-64957789c6b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b0ffeb7b-2b52-4690-a560-ef2937a5564d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm</value>
      <webElementGuid>aa3cba2b-2e77-4ba5-87dd-3beed1c87a63</webElementGuid>
   </webElementProperties>
</WebElementEntity>
