<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_remark</name>
   <tag></tag>
   <elementGuidId>615cf4b1-71e0-40e2-932c-3beefa329236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@class = 'el-textarea__inner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6defc976-542f-47f3-898d-bfbe3aa3b008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-textarea__inner</value>
      <webElementGuid>01ae23fe-da41-4d56-9718-beb9a87827e4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
