<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_uploadedReceipt</name>
   <tag></tag>
   <elementGuidId>d618634e-c74c-48e0-a29e-a029a46d6096</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'upload-filename']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>96750b0e-ea44-4814-a16d-1c76f18981c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upload-filename</value>
      <webElementGuid>3f613c23-f9f4-451d-99a5-20cf972e5160</webElementGuid>
   </webElementProperties>
</WebElementEntity>
